name: quark-bot

services:
    nonebot:
        image: ghcr.io/fllesser/quarkbot:latest
        container_name: quark-bot-nonebot
        environment:
          PORT: 8080
          # 超级用户ID获取方式: [@userinfobot](https://t.me/userinfobot)
          SUPERUSER: 1234567890
          # 机器人 token 获取方式: [@BotFather](https://t.me/BotFather)             
          TELEGRAM_BOT_TOKEN: bot_token
          # 自动转存服务地址
          QAS_ENDPOINT: http://quark-auto-save:5005
          # 前往 quark-auto-save webui 系统配置下拉 API 处获取
          QAS_TOKEN: 1234567890
        restart: unless-stopped
        depends_on: [quark-auto-save]
        networks: [quark-bot-network]

    smartstrm:
      image: cp0204/smartstrm:latest
      container_name: smartstrm
      restart: unless-stopped
      networks: [quark-bot-network]
      ports:
        - 5006:5006
      volumes:
        # 挂载配置目录
        - ./smartstrm/config:/app/config
        # 挂载日志目录，可选
        - ./smartstrm/logs:/app/logs
        # 挂载 STRM 生成目录
        - ./smartstrm/media:/strm
      environment:
        # 管理端口，可选
        - PORT=5006
        # 管理用户名
        - ADMIN_USERNAME=admin
        # 管理用户密码
        - ADMIN_PASSWORD=password

    quark-auto-save:
      image: cp0204/quark-auto-save:latest
      container_name: quark-auto-save
      ports:
        - 5005:5005
      restart: unless-stopped
      networks: [quark-bot-network]
      environment:
        PORT: 5005
        WEBUI_USERNAME: "admin"
        WEBUI_PASSWORD: "password"
      volumes:
        - ./quark-auto-save/config:/app/config
        - ./quark-auto-save/media:/media

    emby:
      image: amilys/embyserver:latest
      container_name: emby
      networks: [quark-bot-network]
      ports:
        - 8096:8096
      environment:
        - TZ=Asia/Shanghai
      volumes:
        - ./emby/config:/config
        # ⚠️ 必须匹配SmartSTRM输出路径
        - ./smartstrm/media:/media
      devices:
        # ✅ 硬件转码支持
        - /dev/dri:/dev/dri  
      restart: always
      # 🔑 关键权限
      privileged: true

networks:
  quark-bot-network:
    name: quark-bot-network
    driver: bridge

