#!/usr/bin/env bash
set -e

cat > /app/.env.prod <<EOF
HOST=0.0.0.0
PORT=${PORT}
SUPERUSERS=["${SUPERUSER}"]
COMMAND_START=["/",""]
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
QAS_ENDPOINT=${QAS_ENDPOINT}
QAS_TOKEN=${QAS_TOKEN}
QAS_PATH_BASE=${QAS_PATH_BASE}
SIMPLE_COMMAND=${SIMPLE_COMMAND}
SIMPLE_SAVE_ROOT=${SIMPLE_SAVE_ROOT}
EOF

exec uv run python -m nonebot run --env prod
